version: '3.9'

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: oops
      POSTGRES_USER: guest

  php:
    extra_hosts:
      - host.docker.internal:host-gateway
    build:
      context: .docker
      dockerfile: php.Dockerfile
    ports:
      - "9000"
    volumes:
      - .:/demo
    working_dir: /demo
#todo: make restart-friendly
    command: >
      sh -c "php composer install && bin/console do:da:cre && bin/console do:mi:mi && php-fpm"

  nginx:
    build:
      context: .docker
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
