version: '3.9'

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: oops
      POSTGRES_USER: guest

  php:
    extra_hosts:
      - host.docker.internal:host-gateway
    image: ghcr.io/genych/php82:latest
    ports:
      - "9000"
    volumes:
      - .:/demo
    working_dir: /demo
    command: >
      sh -c "composer install && bin/console do:da:cre --if-not-exists && bin/console do:mi:mi && php-fpm"
    environment:
      - XDEBUG_MODE=debug,profile
  nginx:
    build:
      context: .docker
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
