version: '3.9'

services:
  red:
    image: redis:7.0.0-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: oops
      POSTGRES_USER: guest

  php:
    image: php:8.1-fpm-alpine
    ports:
      - "9000"
    volumes:
      - .:/demo

  nginx:
    build:
      context: .docker
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
